# GET Request
GET http://localhost:3000/posts HTTP/1.1

#### GET Request
GET http://localhost:3000/swagger HTTP/1.1

### GET Request by ID
GET http://localhost:3000/posts/674f089bae6ecc5f1e199fb0


### POST Request (Create a post)
POST http://localhost:3000/posts/ HTTP/1.1
Content-Type: application/json

{
  "title": "Shopping",
  "description": "meet boss at Accra Mall.",
  "dueDate": "2024-12-11",
  "priority": "Low",
  "status": "completed",
  "createdBy": "63a1f3e7c9a8b6a72d1e78f0"
}


### PUT Request (Update a post)
PUT http://localhost:3000/posts/675045ee222d66eccd296ef9 HTTP/1.1
Content-Type: application/json

 {
    "title": "Team Meeting",
    "description": "Have a meeting with my instructor, I am having a tough time with swagger.",
    "dueDate": "2024-12-10",
    "priority": "medium",
    "status": "approved",
    "createdBy": "63a1f3e7c9a8b6a72d1e78f0"
  }

### This is an HTTP DELETE request targeting a specific resource (post) on a server running locally (localhost) at port 3000.

DELETE http://localhost:3000/posts/67503edc14f5c996dcbaee6a HTTP/1.1

